spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  h2:
    console:
      path: /h2-console
      enabled: true


app:
  dk0124:
    jwt:
      secret: helloWorld
      expirationMs: 9999999
      cookieName: cookiecookie